version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
    environment:
      - VITE_API_URL=http://localhost:8080